export const stockingsData = [
  {
    image: '/images/stocking.svg',
    attachment: '/images/attachment.jpg',
    userTo: 'ReceiverUser',
    userFrom: 'SenderUser',
    nickname: 'nickname1',
    unread: true,
    id: '1',
    favorite: false,
    date: new Date('2022-12-01').toLocaleDateString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    }),
    message:
      'Hello! Merry Christmas to you and your family! I pray and hope God will bless you next year as well.',
  },
  {
    image: '/images/stocking.svg',
    attachment: '/images/attachment.jpg',
    userTo: 'ReceiverUser2',
    userFrom: 'SenderUser2',
    nickname: 'nickname2',
    unread: false,
    id: '2',
    favorite: true,
    date: new Date('2022-12-03').toLocaleDateString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    }),
    message: 'Hello! My name is Esther how are you?',
  },
  {
    image: '/images/stocking.svg',
    attachment: '',
    userTo: 'ReceiverUser3',
    userFrom: 'SenderUser3',
    nickname: 'nickname3',
    unread: true,
    id: '3',
    favorite: false,
    date: new Date('2022-11-25').toLocaleDateString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    }),
    message: 'Hello! My name is Francis how are you?',
  },
  {
    image: '/images/stocking.svg',
    attachment: '',
    userTo: 'ReceiverUser4',
    userFrom: 'SenderUser4',
    nickname: 'nickname4',
    unread: true,
    id: '4',
    favorite: false,
    date: new Date('2022-11-01').toLocaleDateString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    }),
    message: 'Hello! My name is Sungmin how are you?',
  },
  {
    image: '/images/stocking.svg',
    attachment: '/images/attachment.jpg',
    userTo: 'ReceiverUser5',
    userFrom: 'SenderUser5',
    nickname: 'nickname5',
    unread: true,
    id: '5',
    favorite: false,
    date: new Date('2022-11-15').toLocaleDateString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    }),
    message: 'Hello! My name is Hannah how are you?',
  },
  {
    image: '/images/stocking.svg',
    attachment: '',
    userTo: 'ReceiverUser6',
    userFrom: 'SenderUser6',
    nickname: 'nickname6',
    unread: true,
    id: '6',
    favorite: false,
    date: new Date('2022-11-20').toLocaleDateString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    }),
    message: 'Hello! My name is Monkey how are you?',
  },
  {
    image: '/images/stocking.svg',
    attachment: '/images/attachment.jpg',
    userTo: 'ReceiverUser7',
    userFrom: 'SenderUser7',
    nickname: 'nickname7',
    unread: true,
    id: '7',
    favorite: false,
    date: new Date('2022-12-21').toLocaleDateString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    }),
    message: 'Hello! My name is Hippo how are you?',
  },
  {
    image: '/images/stocking.svg',
    attachment: '/images/attachment.jpg',
    userTo: 'ReceiverUser8',
    userFrom: 'SenderUser8',
    nickname: 'nickname8',
    unread: true,
    id: '8',
    favorite: true,
    date: new Date('2022-11-26').toLocaleDateString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    }),
    message: 'Hello! My name is Snake how are you?',
  },
  {
    image: '/images/stocking.svg',
    attachment: '/images/attachment.jpg',
    userTo: 'ReceiverUser9',
    userFrom: 'SenderUser9',
    nickname: 'nickname9',
    unread: true,
    id: '9',
    favorite: false,
    date: new Date('2022-12-01').toLocaleDateString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    }),
    message: 'Hello! My name is Monkey how are you?',
  },
  {
    image: '/images/stocking.svg',
    attachment: '',
    userTo: 'ReceiverUser10',
    userFrom: 'SenderUser10',
    nickname: 'nickname10',
    unread: true,
    id: '10',
    favorite: false,
    date: new Date('2022-12-11').toLocaleDateString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    }),
    message: 'Hello! My name is HooChooh how are you?',
  },
  {
    image: '/images/stocking.svg',
    attachment: '/images/attachment.jpg',
    userTo: 'ReceiverUser11',
    userFrom: 'SenderUser11',
    nickname: 'nickname11',
    unread: true,
    id: '11',
    favorite: false,
    date: new Date('2022-12-21').toLocaleDateString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    }),
    message: 'Hello! My name is Johnny how are you?',
  },
];
